pipeline {

    agent any

    environment {
        PROJECT_NAME = "TorrentAD"
    }

    stages {

        stage('준비') {
            steps {
                cleanWs()
            }
        }

        stage('체크아웃') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[ name: '*/main' ]],
                    extensions: [[
                        $class: 'SubmoduleOption',
                        disableSubmodules: false,
                        parentCredentials: true,
                        recursiveSubmodules: false,
                        reference: '',
                        trackingSubmodules: true
                    ]],
                    submoduleCfg: [],
                    userRemoteConfigs: [[
                        credentialsId: 'github-darkkaiser-credentials',
                        url: 'https://github.com/DarkKaiser/torrent-auto-downloader.git'
                    ]]
                ])
            }
        }

        stage('빌드') {
            steps {
                sh '''
                    cd ./src/TorrentAD
                    sudo chmod 744 ./gradlew
                    sudo ./gradlew clean build

                    cd ../../
                    sudo chown -R jenkins:jenkins ./*
                '''
            }
        }

        stage('배포') {
            steps {
                sh '''
                    sudo cp -f ./dist/taillog /usr/local/torrentad/
                    sudo cp -f ./dist/torrentad.sh /usr/local/torrentad/
                    sudo cp -f ./dist/torrentad-restart.sh /usr/local/torrentad/
                    sudo cp -f ./src/TorrentAD/build/libs/torrentad-1.1.0.jar /usr/local/torrentad/

                    sudo chown pi:staff /usr/local/torrentad/taillog
                    sudo chown pi:staff /usr/local/torrentad/torrentad.sh
                    sudo chown pi:staff /usr/local/torrentad/torrentad-restart.sh
                    sudo chown pi:staff /usr/local/torrentad/torrentad-1.1.0.jar
                '''
            }
        }

        stage('서버 재시작') {
            steps {
                // 경로를 이동하지 않고 서버를 재시작하게 되면 로그 파일의 생성 위치가
                // '/usr/local/torrentad/logs'에 생성되는게 아니라 Jenkins 작업 위치에 생성되게 되는데
                // 이때 'logs' 폴더가 존재하지 않으므로 서버 실행이 실패하게 된다.
                sh '''
                    cd /usr/local/torrentad
                    sudo -u pi /usr/local/torrentad/torrentad-restart.sh
                '''
            }
        }

    }

    post {
        success {
            script {
                telegramSend(message: '【 알림 > Jenkins > ' + env.PROJECT_NAME + ' 】\n\n빌드 작업이 성공하였습니다.\n\n' + env.BUILD_URL)
            }
        }
        failure {
            script {
                telegramSend(message: '【 알림 > Jenkins > ' + env.PROJECT_NAME + ' 】\n\n빌드 작업이 실패하였습니다.\n\n' + env.BUILD_URL)
            }
        }
        always {
            cleanWs()
        }
    }

}
